case $hostname {
  'kvm-compute01':{}
  'kvm-compute02':{}
  'kvm-compute03':{}
  'kvm-compute04':{}
  'kvm-compute05':{}
  'kvm-compute06':{}
  'kvm-compute07':{}
  'kvm-compute08':{}
  'kvm-compute09':{}
  'kvm-compute10':{}
  'kvm-compute11':{}
  'kvm-compute12':{}
  'kvm-compute13':{}
  'kvm-compute14':{}
  'kvm-compute15':{}
  'kvm-compute16':{}
  'kvm-compute17':{}
  'kvm-compute18':{}
  'kvm-compute19':{}
  'kvm-compute20':{}
  'kvm-compute21':{}
  'kvm-compute22':{}
  'kvm-compute23':{}
  'kvm-compute24':{}
  'kvm-compute25':{}
  'kvm-compute26':{}
  'kvm-compute27':{}
  'kvm-compute28':{}
  'kvm-compute29':{}
  'kvm-compute30':{}
  'kvm-compute31':{}
  'kvm-compute32':{}
  'kvm-compute33':{}
  'kvm-compute34':{}
  'kvm-compute35':{}
  'kvm-compute36':{}
  'kvm-compute37':{}
  'kvm-compute38':{}
  'kvm-compute39':{}
  'kvm-compute40':{}
  'kvm-compute41':{}
  'kvm-compute42':{}
  'kvm-compute43':{}
  'kvm-compute44':{}
  'kvm-compute45':{}
  'kvm-compute46':{}
  'kvm-compute47':{}
  'kvm-compute48':{}
  'kvm-compute49':{}
  'kvm-compute50':{}
  default: { notify{"Hey ${hostname}! You don't have individual classes":}}
}
